Shopping_Tutorial/Controllers/BrandController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Shopping_Tutorial.Models;
using Shopping_Tutorial.Repository;

namespace Shopping_Tutorial.Controllers
{
	public class BrandController : Controller
	{
		private readonly DataContext _dataContext;
		public BrandController(DataContext context)
		{
			_dataContext = context;

		}
		public async Task<IActionResult> Index(string Slug = "")
		{
			BrandModel brand = _dataContext.Brands.Where(c => c.Slug == Slug).FirstOrDefault();

			if (brand == null) return RedirectToAction("Index");

			var prodoctsByBrand = _dataContext.Products.Where(p => p.BrandId == brand.Id);

			return View(await prodoctsByBrand.OrderByDescending(p => p.Id).ToListAsync());
		}
	}
}

Shopping_Tutorial/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Shopping_Tutorial.Models;
using Shopping_Tutorial.Repository;

namespace Shopping_Tutorial.Controllers
{
	public class CategoryController : Controller
	{
		private readonly DataContext _dataContext;
		public CategoryController(DataContext context)
		{
			_dataContext = context;

		}

		public async Task<IActionResult> Index(string Slug = "")
		{
			CategoryModel category = _dataContext.Categories.Where(c => c.Slug == Slug).FirstOrDefault();

			if (category == null) return RedirectToAction("Index");

			var prodoctsByCategory = _dataContext.Products.Where(p => p.CategoryId == category.Id);

			return View(await prodoctsByCategory.OrderByDescending(p => p.Id).ToListAsync());
		}
	}
}

Shopping_Tutorial/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Shopping_Tutorial.Repository;

namespace Shopping_Tutorial.Controllers
{
	public class ProductController : Controller
	{
		private readonly DataContext _dataContext;
		public ProductController(DataContext context)
		{
			_dataContext = context;
		}
		public IActionResult Index() { return View(); }

		public async Task<IActionResult> Search(string searchTerm)
		{
			var products = await _dataContext.Products
				.Where(p=> p.Name.Contains(searchTerm) || p.Description.Contains(searchTerm))
				.ToListAsync();
			ViewBag.Keyword = searchTerm;

			return View(products);
		}

		public async Task<IActionResult> Details(int Id)
		{
			if (Id == null) return RedirectToAction("Index");
			var productsById = _dataContext.Products.Where(c => c.Id == Id).FirstOrDefault();
			return View(productsById);
		}
	}
}

Shopping_Tutorial/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="">
	<meta name="author" content="">
	<title>@ViewData["title"]- Admin</title>
	<link href="~/css/bootstrap.min.css" rel="stylesheet">
	<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.0.1/css/font-awesome.css" rel="stylesheet">
	<link href="https://cdn.jsdelivr.net/npm/sweetalert2@11.15.3/dist/sweetalert2.min.css" rel="stylesheet">
	<link href="//cdn.datatables.net/2.1.8/css/dataTables.dataTables.min.css" rel="stylesheet">

	<link href="~/css/font-awesome.min.css" rel="stylesheet">
	<link href="~/css/prettyPhoto.css" rel="stylesheet">
	<link href="~/css/price-range.css" rel="stylesheet">
	<link href="~/css/animate.css" rel="stylesheet">
	<link href="~/css/main.css" rel="stylesheet">
	<link href="~/css/responsive.css" rel="stylesheet">
	<!--[if lt IE 9]>
	<script src="js/html5shiv.js"></script>
	<script src="js/respond.min.js"></script>
	<![endif]-->
	<link rel="shortcut icon" href="images/ico/favicon.ico">
	<link rel="apple-touch-icon-precomposed" sizes="144x144" href="images/ico/apple-touch-icon-144-precomposed.png">
	<link rel="apple-touch-icon-precomposed" sizes="114x114" href="images/ico/apple-touch-icon-114-precomposed.png">
	<link rel="apple-touch-icon-precomposed" sizes="72x72" href="images/ico/apple-touch-icon-72-precomposed.png">
	<link rel="apple-touch-icon-precomposed" href="images/ico/apple-touch-icon-57-precomposed.png">
</head><!--/head-->

<body>
	<header id="header">
		<!--header-->
		<div class="header_top">
			<!--header_top-->
			<div class="container">
				<div class="row">
				</div>
			</div>
		</div><!--/header_top-->

		<div class="header-middle">
			<!--header-middle-->
			<div class="container">
				<div class="row">
					<div class="col-sm-4">
						<div class="logo pull-left">
							<a href="index.html"><img src="images/home/logo.png" alt="" /></a>
						</div>
						<div class="btn-group pull-right">
						</div>
					</div>

				</div>
			</div>
		</div><!--/header-middle-->

		<div class="header-bottom">
			<!--header-bottom-->
			<div class="container">
				<div class="row">
					<div class="col-sm-9">
						<div class="navbar-header">
							<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
								<span class="sr-only">Toggle navigation</span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
							</button>
						</div>
						<div class="mainmenu pull-left">
							<ul class="nav navbar-nav collapse navbar-collapse">
								<li><a asp-area="" asp-controller="Home" asp-action="Index" class="active"><i class="fa fa-home"></i>Home</a></li>
								<li><a asp-controller="Product" asp-action="Index">Sản phẩm</a></li>
								<li><a asp-controller="Category" asp-action="Index">Danh mục</a></li>
								<li><a asp-controller="Brand" asp-action="Index">Thương hiệu</a></li>
								<li><a asp-controller="Order" asp-action="Index">Đơn hàng</a></li>
								<li><a asp-controller="Role" asp-action="Index">Quyền</a></li>
								<li><a asp-controller="User" asp-action="Index">Người dùng</a></li>
								<li><a asp-controller="Contact" asp-action="Index">Liên hệ</a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div><!--/header-bottom-->
	</header><!--/header-->


	<section>
		<div class="container">
			<div class="row">
				@Html.Partial("_NotificationPartial")
				@RenderBody()
			</div>
		</div>
	</section>

	<footer id="footer">
		<!--Footer-->

	</footer><!--/Footer-->



	<script src="~/js/jquery.js"></script>
	<script src="~/js/bootstrap.min.js"></script>
	<script src="~/js/jquery.scrollUp.min.js"></script>
	<script src="~/js/price-range.js"></script>
	<script src="~/js/jquery.prettyPhoto.js"></script>
	<script src="~/js/main.js"></script>
	<script src="~/backend/js/site.js"></script>
	<script src="//cdn.datatables.net/2.1.8/js/dataTables.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.15.3/dist/sweetalert2.all.min.js"></script>
	<script>
		$(function () {
			var message = '@TempData["success"]';
			if (message != '')
				Swal.fire(message);
		});
	</script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Shopping_Tutorial/Areas/Admin/Views/Shared/_NotificationPartial.cshtml
@if (TempData["success"] != null)
{
    <div class=" alert alert-success notification">
        @TempData["success"]
    </div>
}
@if (TempData["error"] != null)
{
    <div class=" alert alert-danger notification">
        @TempData["error"]
    </div>
}

Shopping_Tutorial/Areas/Admin/Views/Shared/_SidebarPartial.cshtml
<div class="left-sidebar" style="border: 2px solid red">
	<h2 style="color:black">DANH MỤC</h2>
	<div class="panel-group category-products" id="accordian">
		<!--category-productsr-->
		<vc:categories></vc:categories>

	</div><!--/category-products-->
	<h2 style="color:black">THƯƠNG HIỆU</h2>
	<div class="panel-group category-products" id="accordian">

		<vc:brands></vc:brands>

	</div><!--/brands_products-->

</div>